dist: trusty
sudo: false
language: node_js
node_js:
  - "6"
addons:
  chrome: stable
before_install:
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run test:once
after_script: greenkeeper-lockfile-upload
after_success:
  - yarn run semantic-release

